const FETCH_JOB = 'FETCH_JOB';
const NEW_POST = 'NEW_POST';

const GET_CONTRACTOR = 'GET_CONTRACTOR';
const POST_CONTRACTOR = 'POST_CONTRACTOR';
const PUT_CONTRACTOR = 'PUT_CONTRACTOR';

const GET_CUSTOMER = 'GET_CUSTOMER';
const POST_CUSTOMER = 'POST_CUSTOMER';
const PUT_CUSTOMER = 'PUT_CUSTOMER';

const GET_SEALS_PERSON = 'GET_SEALS_PERSON';
const POST_SEALS_PERSON = 'POST_SEALS_PERSON';
const PUT_SEALS_PERSON = 'PUT_SEALS_PERSON';

const GET_INSURANCE_COMPANY = 'GET_INSURANCE_COMPANY';
const POST_INSURANCE_COMPANY = 'POST_INSURANCE_COMPANY';
const PUT_INSURANCE_COMPANY = 'PUT_INSURANCE_COMPANY';

export {
    FETCH_JOB, NEW_POST,
    GET_CONTRACTOR, POST_CONTRACTOR, PUT_CONTRACTOR,
    GET_CUSTOMER, POST_CUSTOMER, PUT_CUSTOMER,
    GET_SEALS_PERSON, POST_SEALS_PERSON, PUT_SEALS_PERSON,
    GET_INSURANCE_COMPANY, POST_INSURANCE_COMPANY, PUT_INSURANCE_COMPANY
};