const FETCH_JOB = 'FETCH_JOB';
const NEW_POST = 'NEW_POST';

const GET_CONTRACTOR = 'GET_CONTRACTOR';
const POST_CONTRACTOR = 'POST_CONTRACTOR';

export { FETCH_JOB, NEW_POST, GET_CONTRACTOR, POST_CONTRACTOR };