export const stages = [
    'ICA',
    'FE ESTIMATE',
    'FILE INSURANCE CLAIM',
    'INSURANCE INSPECTION',
    'FE CONTRACT',
    'SUBMIT TO INSURANCE',
    'INSURANCE APPROVAL',
    'ORDER MATERIALS',
    'TRADE COMPLETION',
    'SUPPLEMENT',
    'FINAL INVOICE']